### ISSUE TITLE
Error in pollyfills.ts

### ISSUE THREAD

**Issue by enterpriseSoftware** [daviddt/angular2-lazy-load-example#1]
^[[1m^[[31mERROR in ./src/polyfills.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/xxxx/OVSLazyLoad/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/Users/xxxx/OVSLazyLoad/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/Users/xxxx/OVSLazyLoad/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/xxxx/OVSLazyLoad/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi polyfills^[[39m^[[22m

^[[1m^[[31mERROR in ./src/vendor.ts
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (/Users/xxxx/OVSLazyLoad/node_modules/awesome-typescript-loader/src/instance.ts:266:72)
    at Object.ensureInstance (/Users/xxxx/OVSLazyLoad/node_modules/awesome-typescript-loader/src/instance.ts:145:5)
    at compiler (/Users/xxxx/OVSLazyLoad/node_modules/awesome-typescript-loader/src/index.ts:37:20)
    at Object.loader (/Users/xxxx/OVSLazyLoad/node_modules/awesome-typescript-loader/src/index.ts:18:18)
 @ multi vendor^[[39m^[[22m

"startuplog.txt" 38L, 2535C

**Comment by cecilphillip** [comment]
I'm getting the same error... not quite sure what the root cause is yet

**Comment by cecilphillip** [comment]
@enterpriseSoftware there's a bug filed on the repo https://github.com/s-panferov/awesome-typescript-loader/issues/190

**Comment by fazalWahid56** [comment]
same error here.

**Comment by mii9000** [comment]
I get the same error. Any solution found?
